name: Deploy

on: 
    pull_request:
        branches:
            - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to production
        uses: ObinnaVic/render-deploy-action@v0.0.8
        with: 
          service-id: ${{ secrets.SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}


          