name: Deploy

on: 
    pull_request:
        branches:
            - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
      
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install and configure Nginx
        run: |
          sudo apt-get update
          sudo apt-get install -y nginx
          sudo cp nginx.conf /etc/nginx/sites-available/fastapi
          sudo nginx -t
          sudo systemctl start nginx

      - name: Deploy to Render
        run: |
          curl -X POST "https://api.render.com/v1/services/${{ secrets.SERVICE_ID }}/deploys" \
          -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
          -H "Accept: application/json" \
          -H "Content-Type: application/json" \
          -d '{}'


          