name: test

on: 
  push:
    branches:
      - added_api

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: python:3.12
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Install dependencies
        run: |
          python3 -m venv venv
          source venv/bin/activate
          pip install flake8 pytest pytest-cov
          pip install -r requirements.txt
      
      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings
          flake8 . --count --exit-zero --max-complexity=10 --statistics
      
      - name: Run tests with pytest
        run: |
          source venv/bin/activate
          pytest

